README.md
code/enumerable/select-first-vs-detect.rb

Hi, I figured out that some people use the wrong way to select the first element of an Enumerable that match to _x_.
I wrote a test case that represent the performance issue when using the wrong way.
Bonus : I fixed a test case title in the readme.

Added benchmark for select the first element matching in an Enumerable.

---

README.md
code/array/count-vs-size.rb

Although, `#count` can be given an argument or take a block, it can also return the size of a collection similar to `#size` as stated in this [blog post](http://batsov.com/articles/2014/02/17/the-elements-of-style-in-ruby-number-13-length-vs-size-vs-count/).
In this pull request, I've added a benchmark for `#count` vs. `#size` and updated the README accordingly.

Add benchmark for #count vs. #size.

---

README.md
code/enumerable/each-vs-for-loop.rb

I thought it would be interesting to see how `#each` compares to a regular for loop. So in this pull request I've added the code for the benchmark and an updated README.

Add benchmark for #each vs. for loop.

---

README.md

This example showed up twice in the README. Closing this pull will fix the duplication.

Remove duplicated example in README.md

---

README.md
code/general/assignment.rb

The parallel assignment benchmark only allocates an array because the assignment expression is the last expression in the method (and so its result is returned to the caller). If Ruby detects that an expression's result is unused (as would be the case with most assignment expressions), it will avoid allocating the array and just assign directly.
Inspecting the bytecode generated for parallel assignment in both cases shows off this optimisation:
```
λ ruby --dump=insns -e 'a, b, c = 1, 2, 3'
== disasm: <RubyVM::InstructionSequence:<main>@-e>======================
local table (size: 4, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, keyword: 0@5] s1)
[ 4] a          [ 3] b          [ 2] c
0000 trace            1                                               (   1)
0002 duparray         [1, …
```

Return nil from assignment benchmarks

---

README.md
code/string/match-vs-=~.rb

If you're only looking for presence of a match and don't need the matchdata, use String#=~ 
https://github.com/schneems/rails/commit/1bf50badd943e684a56a03392ef0ddafefca0ad7#commitcomment-12572839

String#=~ faster than String#match

---

README.md

I think ... :rabbit: 
* `Hash.fetch` -> `Hash#fetch`
* `Hash#[]` -> `Hash[]` on bracket-vs-dup

Fix idiom title

---

README.md
code/general/array-argument-vs-splat-arguments.rb

Invoking a function that expects multiple splat arguments when all you have is an Array is quite costly (100x). Also, it won't work with sufficiently large arrays as seen [here](http://stackoverflow.com/questions/28703587/systemstackerror-when-pushing-more-than-130798-objects-into-an-array).

Add Function with single Array argument vs splat arguments example

---

README.md
code/proc-and-block/proc-call-vs-yield.rb

What is slower is to bind the block to a variable, not calling it, just try my version and you will see that slow and slow4 are both 4.x slower than yield alone.

yield vs block.call misleading

---

README.md
code/string/sub-vs-chomp.rb

Of course only for removing characters from the end of a string. Likewise, `#chomp!` is faster than `#sub!`, although “only” by a factor 2…
Tested with the 4 rubies I have installed:
```
» ruby -v code/string/sub-vs-chomp.rb
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
Calculating -------------------------------------
String#sub/regexp/    38.068k i/100ms
String#chomp'string'    78.284k i/100ms
-------------------------------------------------
String#sub/regexp/    560.625k (±17.1%) i/s -      2.703M
String#chomp'string'      2.704M (±18.6%) i/s -     12.839M
Comparison:
String#chomp'string':  2703881.6 i/s
String#sub/regexp/:   560625.4 i/s - 4.82x slower
```
```
» ruby -v code/string/sub-vs-chomp.rb
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin13.0] …
```

String#chomp can be faster than String#sub

---

README.md
code/array/insert-vs-unshift.rb

I needed to insert items in the beginning of the array and unshift turns out to be much faster. The comparison here is for a larger array and insert of the beginning of the same array. Initially i did the comparison between `fast` and `slow`, but this does not reflect correctly the difference in the performance.
````ruby
def fast
[].unshift(1)
end
def slow
[].insert(0, 1)
end
````
Let me know if further information is required.

Array insert vs unshift

---

README.md
code/string/sub-vs-chomp.rb

$ matches the end of a line. Regular expressions in Ruby default to multiline mode. The regex should match chomp's default behavior.
Thanks @sshaw for pointing out this mistake in #47.

sub-vs-chomp must use \z instead of $

---

README.md

I think that 414f86f6 introduced the same sentence (regarding `Exception2MessageMapper`) twice so I removed the latter reference (accidentally placed within a code sample).

remove an accidentally duplicated sentence

---

README.md
code/enumerable/inject-symbol-vs-block.rb

Someone had asked me about using the block short form vs manually entering the code.
Turns out, in 1.8.7, using the block was 1.7x slower, but since then, the symbol form is a little quicker.
Thanks for this repo

compare inject block vs manual entries

---

README.md
code/hash/merge-bang-vs-merge-vs-dup-merge-bang.rb

'fast' method has different result from other methods. Because:
```ruby
ORIGINAL_HASH = { foo: "foo" }
#fast
{ foo: 'bar' }.merge!(ORIGINAL_HASH)
#=> {:foo=>"foo"}
#slow
ORIGINAL_HASH.merge(foo: 'bar')
#=> {:foo=>"bar"}
#slow_dup
ORIGINAL_HASH.dup.merge!(foo: 'bar')
#=> {:foo=>"bar"}
#new fast
{ foo: 'bar' }.merge!(ORIGINAL_HASH){ |_key, left, _right| left }
#=> {:foo=>"bar"}
```

little fix for the hash merge comparison

---

README.md
code/hash/merge-vs-double-splat-operator.rb

Shows how the double splat operator adds faster Hash merging compared to the `Hash#merge` method.

Add double splat operator vs merge

---

README.md
code/general/format-vs-round-and-to-s.rb

This compares two alternatives for starting with a floating point
number, transform it into a formatted string with a specific number
of digits after the point.

Add benchmark for format() vs round().to_s

---

README.md

Move example of `attr_accessor vs getter and setter` from String to General.

Move `attr_accessor vs getter and setter` from String to General

---

README.md
code/string/remove-extra-spaces-or-other-chars.rb

The code is tested against contiguous spaces, but should work for other contiguous chars too.

Remove extra spaces (or other contiguous chars)

---

README.md

Add command that runs the script

---

README.md
code/general/inheritance-check.rb

`ClassA <= ClassB` is a much faster inheritance check compared to `ClassA.ancestors.include?(ClassB)`.

Add inheritance check

---

README.md
code/date/iso8601-vs-parse.rb
code/time/iso8601-vs-parse.rb

Unless you're dealing with historic times, you should avoid using `DateTime` as outlined in the Ruby docs:
https://ruby-doc.org/stdlib-2.3.0/libdoc/date/rdoc/DateTime.html#class-DateTime-label-When+should+you+use+DateTime+and+when+should+you+use+Time-3F and the http://rubocop.readthedocs.io/en/latest/cops_style/#styledatetime cop. This is why I didn't benchmark it.

Add ISO8601 string parsing comparison for `Time` and `Date`

---

README.md
code/string/dup-vs-unary-plus.rb

As inspired by the [Performance/UnfreezeString](http://rubocop.readthedocs.io/en/latest/cops_performance/#performanceunfreezestring) Rubocop rule.

Add comparison for unfreezing strings in `frozen_string_literal: true` files

---

README.md
code/proc-and-block/proc-call-vs-yield.rb

In Ruby 2.5, passing through a `block` argument has become a lot faster.
I renamed the 'block argument' benchmark because I felt the old name was misleading as the fastest on Ruby 2.5.

Update `Proc#call` and block arguments vs `yield` for Ruby 2.5 and 2.6

---

README.md
code/array/array-new-vs-fixnum-times-map.rb

When you need to map the result of a block invoked a fixed amount of times, you have an option between:
```
Array.new(n) { ... }
```
and:
```
n.times.map { ... }
```
The latter one is about 60% slower for `n = 10`, which goes down to around 40% for `n > 1_000.`
_Note: logarithmic scale!_

Add benchmark for Array#new vs. Fixnum#times + map

---

README.md
code/hash/update-vs-[]=.rb

**Hash#update** is an alias for **Hash#merge!**. Ergo, the comparision between **Hash#update** and **Hash#[]=** should have similar outcome.
Ref https://github.com/JuanitoFatas/fast-ruby/issues/194

Hash#update() vs Hash#[]=

---

README.md
code/string/casecmp-vs-downcase-==.rb

[`String#casecmp?`](https://ruby-doc.org/core-2.4.0/String.html#method-i-casecmp-3F) was introduced in Ruby 2.4

Update benchmark with `String#casecmp?` example

---

README.md
code/general/constantize-vs-comparison.rb

If you're writing a Rails app, you may reach for `String#constantize` (provided by [Active Support Core Extensions](https://guides.rubyonrails.org/active_support_core_extensions.html#constantize)) when you have a variable that may resolve to a class name and your control flow is to execute that classes code in some manner.
This benchmarks using `String#constantize` vs a simple comparison, showing the latter is much faster.

String#constantize vs simple comparison

---

README.md
code/array/array-concat-vs-+.rb

As discussed [#165](https://github.com/JuanitoFatas/fast-ruby/issues/165)

Add Array#concat vs Array#+

---

CONTRIBUTING.md
README.md

This PR is fix some typo.
- s/satisfiy/satisfy/
- s/exeptions/exceptions/

Fix some typos

---

README.md
code/string/===-vs-=~-vs-match.rb

The repository already mentioned Regexp#match? but didn't provide a benchmark for it. For the sake of completion, I've also included Regexp#match so nobody mixes them up.

Add Regexp#match? and Regexp#match to regex matching benchmark

---

.github/workflows/benchmarks.yml

TruffleRuby is a high speed implementation of Ruby. It should run all of these benchmarks just fine. I think it'd be interesting to see the results. I suspect in many cases, the JIT can optimize the different variants of a given benchmark so that there is no clear winner. In cases where it does not, that indicates an opportunity for the JIT to improve.

Run benchmarks on TruffleRuby in CI.

---

.github/workflows/benchmarks.yml

This PR changes the setup of the workflow to only set the `SHARE` env variable if the current branch is main.
I have no way of testing this completely until is merged into main.
I first tried to set either `1` or an empty string to the SHARE variable but it didn't work (bechmarks.ips only checks if the env variable is set, not the value, so an empty var triggers the sharing too).
Instead, I went with the solution from the docs here https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files, making the step that sets the env variable conditional to the branch name.
Fixes https://github.com/fastruby/fast-ruby/issues/207

Set the SHARE env variable only if current branch is main

---

code/range/cover-vs-include.rb

add value.between?(start, end) to range compares. 
It tested fastest against others on MRI 2.2.3, and tied for best on JRuby 9.0.4.0

Add val.between?(start, end) to range comparisons

---

Gemfile

Fixes #217
```
➜  fast-ruby git:(main) bundle exec ruby code/general/constantize-vs-comparison.rb
code/general/constantize-vs-comparison.rb:1:in `require': cannot load such file -- active_support/core_ext/string/inflections.rb (LoadError)
from code/general/constantize-vs-comparison.rb:1:in `<main>'
➜  fast-ruby git:(main) bundle exec ruby code/general/raise-vs-e2mmap.rb
code/general/raise-vs-e2mmap.rb:2:in `require': cannot load such file -- e2mmap (LoadError)
from code/general/raise-vs-e2mmap.rb:2:in `<main>'
```
```
➜  fast-ruby git:(fix_217_add_e2mmap_and_activesupport_to_gemfile) ✗ bundle exec ruby code/general/constantize-vs-comparison.rb
Warming up --------------------------------------
using an if statement
697.251k i/100ms
String#constantize   418.324k i/100ms
Calculating …
```

Fix 217: Add activesupport and e2mmap to Gemfile

---

code/string/concatenation_randomized.rb

proposition for https://github.com/fastruby/fast-ruby/issues/158 fix.

Randomized string concat

---

README.md
code/string/gsub-vs-tr-vs-delete.rb

This benchmark proves that delete is faster than tr and both are considerably faster than gsub when removing a character from a string.

compare gsub vs tr vs delete to remove character from string

---

.github/workflows/benchmarks.yml

This PR fixes issues when running old Ruby versions in CI using `ubuntu-latest`.
The sig fault error seems to be a known issue https://github.com/ruby/setup-ruby/issues/496#issuecomment-1520667671
The workaround is to use ubuntu 20.04 for older rubies instead of ubuntu-latest.
(CI was running fine, it was cancelled to avoid flooding ips.fastruby.io with benchmarks)

Run old rubies with Ubuntu 20 in CI

---

README.md

I believe the url is not related to the repository, probably the domain got sold :D

link in readme is not relevant anymore 

---

.github/workflows/benchmarks.yml

Split  CI builds per OS, the 'jruby-9.1' and 'truffleruby-22' are not supported at Ubuntu latest which means Ubuntu 24.04.

Fix Ubuntu version
